RD-9983 plugin antl 4 parser
raw-labs/snapi pull request #263
Opened 2023-11-13 10:38 UTC by Alexzerntev

- Switched Truffle compiler to antlr4 parser

2023-11-15 10:51 UTC, Alexzerntev commented
/publish

2023-11-15 13:53 UTC, Alexzerntev commented
/publish

2023-11-16 09:12 UTC, Alexzerntev commented
/publish

2023-11-16 16:06 UTC, Alexzerntev commented
/publish

2023-11-17 13:14 UTC, Alexzerntev commented
/publish

2023-11-20 08:39 UTC, bgaidioz commented on snapi-frontend/src/main/scala/raw/compiler/rql2/antlr4/RawSnapiVisitor.scala
> +            .getOrElse(ErrorType())
`ErrorType` isn't an `Rql2TypeWithProperties`, I suppose the `asInstanceOf` would fail if a type doesn't parse?

Maybe if the type doesn't parse, the properties should be parsed but ignored?

2023-11-20 09:25 UTC, Alexzerntev commented
/publish

2023-11-22 16:40 UTC, miguelbranco80 requested changes
There are issues with the CompilerParserException which we'd need to reconsider!

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +      ParseFailure(parseResult.errors)
We need to handle NonFatal exceptions to get JIRA reports, as was done before.
Means we need to build the program context so we have everything we need to report in the JIRA crash report.

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +          GetTypeFailure(tree.errors)
Two observations:
* We need to handle NonFatal exceptions to get JIRA reports, just as was done before.
* How are errors handled now? Can we successfully build a TreeWithPositions object with a broken tree? That is a significant API change which means we would need to always check the validity of the parse tree after building it. In the past, for safety, it would blow up on building.

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +          GetProgramDescriptionFailure(tree.errors)
Need to handle NonFatal

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +          ValidateResponse(parseResult.errors)
Same issue with NonFatal.

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +          GetTypeFailure(tree.errors)
And if we are to change the API - which I'm not against but it will be time-consuming to get right I believe - we need a full review because I'm fairly confident we have many situations where we build the TreeWithPositions and wouldn't be checking that it parsed. Because in the past, it would just blow up and not even build the object.

And if we were to do that, we'd then have to review the existence of the CompilerParserException itself.

Or otherwise, we change CompilerParserException to carry multiple errors and start throwing as we used to do before, in the base TreeWithPositions.

2023-11-22 16:40 UTC, miguelbranco80 commented on snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala
> +          GetTypeFailure(tree.errors)
For instance, look at this inside RawLanguage:

```
} catch (RuntimeException e) {
  if (e.getCause() instanceof CompilerParserException) {
    CompilerParserException ex = (CompilerParserException) e.getCause();
```

This would need to be adapted.

But it's not just places where CompilerParserException is used. After all, removing it would force you to find cases where it's leftover. But there's also CompilerException. Notice that CompilerParserException is a child of CompilerException so we'd also need to analyze every case where CompilerException happens and understand if we need to add the extra 'parse check OK' is needed or not, and propagate errors in the "consumer".

2023-11-23 14:32 UTC, miguelbranco80 commented
It seems that if we were to delete CompilerParserException and CompilerExecutionException.
In the case of CompilerExecutionException we would replace it by throw CompilerException.
In the case of CompilerParserException, it's case-by-case basis: either replace by checking that parse errors are empty, or do as you're doing in the PR...

2023-11-24 13:01 UTC, Alexzerntev commented
/publish

2023-11-24 13:51 UTC, datYori commented
/publish

2023-11-24 13:54 UTC, datYori commented
/publish

2024-01-11 13:22 UTC, Alexzerntev commented
Branch to be deleted. The branch that will be merged is : https://github.com/raw-labs/snapi/pull/317

2024-01-16 10:43 UTC, closed without merging