RD-9092 Implement Http Package in Truffle
raw-labs/snapi pull request #3
Opened 2023-06-30 14:56 UTC by Alexzerntev

- Implemented Http Package
- Added binary const type
- Converted `Exceptions` to `RawTruffleExceptions` , 
- Fixed location settings

2023-07-03 11:30 UTC, miguelbranco80 requested changes
Some changes are needed I believe on the error handling part.

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpUrlDecodeNode.java
> +        return URLDecoder.decode(str, StandardCharsets.UTF_8);
No need for Truffle boundaries? Do we have a better understanding of when those are needed?
If this would be part of a larger AST, would it then be necessary?

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpUrlEncodeNode.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8);
(Same comment/question regarding Truffle boundaries.)

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpUrlEncodeNode.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8);
Any need to handle URLEncoder exceptions? Can this fail?
If so @bgaidioz , should it be triable?

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpReadNode.java
> +            return ObjectTryable.BuildFailure(e.getMessage());
Suggest you distinguish LocationException - whose message is "safe to show" to the users - from all the others, which are internal exceptions whose text we must not share to users for security reasons. In those cases, send a more generic message and log the original exception.

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/collection/CollectionTupleAvgNode.java
> +        } catch (RawTruffleRuntimeException | UnsupportedMessageException | UnknownIdentifierException |
Same comment on exception as early, to distinguish "RawExceptions" whose text is always safe to share, from all others.

2023-07-03 11:30 UTC, miguelbranco80 commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/location_package/LocationBuildNode.java
> +            throw new RawTruffleRuntimeException("Error while building LocationSettingValue", this);
This message is not helpful to a user. It also talks about internal implementation. Remember that Raw Exceptions become user-visible errors.
Also, it should start with 'small caps' if it were a user-visible error (which it's not)
When can this happen? Is this an assertion error otherwise? I was assuming the type system protects some of this, but may be mistake. Perhaps @bgaidioz can comment further.

2023-07-03 11:50 UTC, bgaidioz commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpUrlEncodeNode.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8);
I understand `.encode` doesn't fail to encode. It only throws `NullPointerException` when the charset is null. That's why it wasn't made tryable.

2023-07-03 12:36 UTC, Alexzerntev commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpReadNode.java
> +            return ObjectTryable.BuildFailure(e.getMessage());
The other are truffle exceptions of dynamic objects. Aren't they safe to show?

2023-07-03 13:35 UTC, bgaidioz commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/location_package/LocationBuildNode.java
> +            throw new RawTruffleRuntimeException("Error while building LocationSettingValue", this);
I understand the same: the calls to `InteropLibrary` methods can throw (if one passes an inexisting key to 'readMember', if one calls `readArrayElement` with a wrong index). It is a system error, we have a bug. This should be reported as an `"internal error"` to a user.

In CSV the same happens, when we read into a record or write from a record. I patched the code in an ongoing PR to report `RawTruffleRuntimeException("internal error", cause, this)`.

Maybe we need something consistent to throw all over the place? `throw new RawInternalError(cause, node)`?

2023-07-03 13:39 UTC, Alexzerntev commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/location_package/LocationBuildNode.java
> +            throw new RawTruffleRuntimeException("Error while building LocationSettingValue", this);
Makes sense to me

2023-07-04 12:09 UTC, Alexzerntev commented
@miguelbranco80 @bgaidioz All the fixes for comments of this PR are fixed in https://github.com/raw-labs/snapi/pull/6 . Which is also merged in this one.

2023-07-04 12:09 UTC, bgaidioz commented on raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/http_package/HttpReadNode.java
> +            return ObjectTryable.BuildFailure(e.getMessage());
I understand this is fixed in the latest version of the code (only `LocationException` and `IOException` are caught).

2023-07-04 12:10 UTC, bgaidioz approved these changes

2023-07-05 07:12 UTC, miguelbranco80 requested changes
Some additional ones.

2023-07-05 08:15 UTC, miguelbranco80 approved these changes
Thank you!

2023-07-05 08:18 UTC, merged